### ISSUE TITLE
Summary - Almost Exceeds Expecations

### ISSUE THREAD

**Issue by Tereseus** [stephen-salyer/f1-3-c2p1-colmar-academy#4]
Your project is almost perfect, You are near the highest percentile as you did this project almost perfectly and actually made it look better than the solution in some ways. I do not have much to say other than that the only thing you could make better is to work on the nav bar a little bit. Great job, keep up the good work!

**Comment by stephen-salyer** [comment]
Thank you so much! This means a lot to me!
